import { PromptTemplate } from '@langchain/core/prompts';
import { getLLM } from '../llm/client.js';
import { DedupInputSchema } from '../types.js';
import type { Challenge, DedupOutput, UUID } from '../types.js';
import { getChallengeById } from '../storage/database.js';

const DEDUP_TEMPLATE = `You are the deduplication and conflict detection system for Friction. You receive a list of challenges generated by different personas and need to:

1. GROUP semantically similar challenges together (same core issue, different phrasing)
2. DETECT direct contradictions between challenges from different personas

CHALLENGES:
{challengesJson}

For grouping:
- Challenges that target the same assumption with similar concerns should be grouped
- Only group challenges that are essentially saying the same thing
- When grouped, merge the headline and body into a single coherent challenge

For conflicts:
- Two challenges directly contradict each other (one says X, another says not-X)
- This is NOT about disagreeing on severity — it's about factual/logical contradiction
- Return as conflict pairs`;

export class Deduplicator {
  async deduplicate(challenges: Challenge[]): Promise<{
    mergedChallenges: Challenge[];
    conflictPairs: Array<{ challengeA: UUID; challengeB: UUID; description: string }>;
  }> {
    if (challenges.length <= 1) {
      return { mergedChallenges: challenges, conflictPairs: [] };
    }

    try {
      const llm = getLLM('dedup');
      const prompt = PromptTemplate.fromTemplate(DEDUP_TEMPLATE);
      const chain = prompt.pipe(llm.withStructuredOutput(DedupInputSchema));

      const challengesJson = JSON.stringify(
        challenges.map((c) => ({
          id: c.id,
          persona: c.personaName,
          targets: c.targets,
          severity: c.severity,
          category: c.category,
          headline: c.headline,
          body: c.body,
        })),
        null,
        2,
      );

      const result = await chain.invoke({ challengesJson }) as DedupOutput;

      // Build merged challenges: keep challenges that weren't in any group,
      // and create merged ones for groups
      const groupedIds = new Set<string>();
      for (const group of result.groups) {
        for (const cid of group.challengeIds) {
          groupedIds.add(cid);
        }
      }

      // Handle merged groups
      const mergedMap = new Map<string, Challenge>();
      for (const group of result.groups) {
        // Keep the highest severity challenge from the group as the merged one
        const groupChallenges = group.challengeIds
          .map((id) => challenges.find((c) => c.id === id))
          .filter((c): c is Challenge => c !== undefined);

        if (groupChallenges.length === 0) continue;

        const severityOrder: Record<string, number> = { blocker: 0, major: 1, minor: 2, informational: 3 };
        groupChallenges.sort((a, b) => (severityOrder[a.severity] ?? 99) - (severityOrder[b.severity] ?? 99));

        const primary = groupChallenges[0]!;
        primary.headline = group.mergedHeadline;
        primary.body = group.mergedBody;
        primary.conflictWith = [];

        mergedMap.set(primary.id, primary);
      }

      // Add ungrouped challenges
      for (const c of challenges) {
        if (!groupedIds.has(c.id)) {
          mergedMap.set(c.id, c);
        }
      }

      // Tag conflict pairs
      const conflictPairs: Array<{ challengeA: UUID; challengeB: UUID; description: string }> = [];
      for (const conflict of result.conflicts) {
        const challengeA = challenges.find((c) => c.id === conflict.challengeIdA);
        const challengeB = challenges.find((c) => c.id === conflict.challengeIdB);

        if (challengeA && challengeB) {
          // Tag both challenges with conflict info
          const mergedA = mergedMap.get(challengeA.id);
          const mergedB = mergedMap.get(challengeB.id);
          if (mergedA) mergedA.conflictWith.push(challengeB.id);
          if (mergedB) mergedB.conflictWith.push(challengeA.id);

          conflictPairs.push({
            challengeA: challengeA.id,
            challengeB: challengeB.id,
            description: conflict.description,
          });
        }
      }

      return {
        mergedChallenges: Array.from(mergedMap.values()),
        conflictPairs,
      };
    } catch (error) {
      // If dedup fails, return original challenges unchanged
      console.error('Deduplication failed, returning original challenges:', error);
      return { mergedChallenges: challenges, conflictPairs: [] };
    }
  }
}